<?php
defined('BASEPATH') or exit('No direct script access allowed');

class Exam_model extends CI_Model
{

	public function countAllAnswer()
	{
		$hasil = floor(base64_decode($this->input->post('soal1')))+floor(base64_decode($this->input->post('soal2')))+floor(base64_decode($this->input->post('soal3')))+floor(base64_decode($this->input->post('soal4')))+floor(base64_decode($this->input->post('soal5')))+floor(base64_decode($this->input->post('soal6')))+floor(base64_decode($this->input->post('soal7')))+floor(base64_decode($this->input->post('soal8')))+floor(base64_decode($this->input->post('soal9')))+floor(base64_decode($this->input->post('soal10')))+floor(base64_decode($this->input->post('soal11')))+floor(base64_decode($this->input->post('soal12')))+floor(base64_decode($this->input->post('soal13')))+floor(base64_decode($this->input->post('soal14')))+floor(base64_decode($this->input->post('soal15')))+floor(base64_decode($this->input->post('soal16')))+floor(base64_decode($this->input->post('soal17')))+floor(base64_decode($this->input->post('soal18')))+floor(base64_decode($this->input->post('soal19')))+floor(base64_decode($this->input->post('soal20')))+floor(base64_decode($this->input->post('soal21')))+floor(base64_decode($this->input->post('soal22')))+floor(base64_decode($this->input->post('soal23')))+floor(base64_decode($this->input->post('soal24')))+floor(base64_decode($this->input->post('soal25')))+floor(base64_decode($this->input->post('soal26')))+floor(base64_decode($this->input->post('soal27')))+floor(base64_decode($this->input->post('soal28')))+floor(base64_decode($this->input->post('soal29')))+floor(base64_decode($this->input->post('soal30')))+floor(base64_decode($this->input->post('soal31')))+floor(base64_decode($this->input->post('soal32')))+floor(base64_decode($this->input->post('soal33')))+floor(base64_decode($this->input->post('soal34')))+floor(base64_decode($this->input->post('soal35')))+floor(base64_decode($this->input->post('soal36')))+floor(base64_decode($this->input->post('soal37')))+floor(base64_decode($this->input->post('soal38')))+floor(base64_decode($this->input->post('soal39')))+floor(base64_decode($this->input->post('soal40')))+floor(base64_decode($this->input->post('soal41')))+floor(base64_decode($this->input->post('soal42')))+floor(base64_decode($this->input->post('soal43')))+floor(base64_decode($this->input->post('soal44')))+floor(base64_decode($this->input->post('soal45')))+floor(base64_decode($this->input->post('soal46')))+floor(base64_decode($this->input->post('soal47')))+floor(base64_decode($this->input->post('soal48')))+floor(base64_decode($this->input->post('soal49')))+floor(base64_decode($this->input->post('soal50')));

    	return $hasil;
	}

}